# Generated by Django 3.2.5 on 2021-08-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=140)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
