# Generated by Django 3.2.5 on 2021-08-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=140)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
